name: tp0
services:
    server:
        container_name: server
        image: server:latest
        entrypoint: /server
        networks:
        - testing_net
        volumes:
        - ./server/config.yaml:/config.yaml  
    
    client1:
        container_name: client1
        image: client:latest
        entrypoint: /client
        environment:
        - CLI_ID=1
        networks:
        - testing_net
        depends_on:
        - server
        volumes:
        - ./client/config.yaml:/config.yaml 
        - ./.data/agency-1.csv:/.data/agency-1.csv
    
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.25.125.0/24
    