name: tp0
services:
    server:
        container_name: server
        image: server:latest
        entrypoint: python3 /main.py
        environment:
        - PYTHONUNBUFFERED=1
        networks:
        - testing_net
        volumes:
        - ./server/config.ini:/config.ini  
    
    client1:
        container_name: client1
        image: client:latest
        entrypoint: /client
        environment:
        - CLI_ID=1
        - CLI_NOMBRE=Juan
        - CLI_APELLIDO=Perez
        - CLI_DNI=12345678
        - CLI_NACIMIENTO=1990-01-01
        - CLI_NUMERO=123456789
        networks:
        - testing_net
        depends_on:
        - server
        volumes:
        - ./client/config.yaml:/config.yaml 
    
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.25.125.0/24
    