name: tp0
services:
    server:
        container_name: server
        image: server:latest
        entrypoint: /server
        networks:
        - testing_net
        volumes:
        - ./server/config.ini:/config.ini  
    
    client1:
        container_name: client1
        image: client:latest
        entrypoint: /client
        environment:
        - CLI_ID=1
        networks:
        - testing_net
        depends_on:
        - server
        volumes:
        - ./client/config.yaml:/config.yaml 
        - ./.data/agency-1.csv:/.data/agency-1.csv
    
    client2:
        container_name: client2
        image: client:latest
        entrypoint: /client
        environment:
        - CLI_ID=2
        networks:
        - testing_net
        depends_on:
        - server
        volumes:
        - ./client/config.yaml:/config.yaml 
        - ./.data/agency-2.csv:/.data/agency-2.csv
    
    client3:
        container_name: client3
        image: client:latest
        entrypoint: /client
        environment:
        - CLI_ID=3
        networks:
        - testing_net
        depends_on:
        - server
        volumes:
        - ./client/config.yaml:/config.yaml 
        - ./.data/agency-3.csv:/.data/agency-3.csv
    
    client4:
        container_name: client4
        image: client:latest
        entrypoint: /client
        environment:
        - CLI_ID=4
        networks:
        - testing_net
        depends_on:
        - server
        volumes:
        - ./client/config.yaml:/config.yaml 
        - ./.data/agency-4.csv:/.data/agency-4.csv
    
    client5:
        container_name: client5
        image: client:latest
        entrypoint: /client
        environment:
        - CLI_ID=5
        networks:
        - testing_net
        depends_on:
        - server
        volumes:
        - ./client/config.yaml:/config.yaml 
        - ./.data/agency-5.csv:/.data/agency-5.csv
    
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.25.125.0/24
    